name: Debricked scan test v1.1

on: [push, pull_request_target, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
          # DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
          
